apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cardb
  name: cardb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cardb
    spec:
      containers:
      - image: fraj24/cardb
        name: cardb
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cardb
  name: cardb
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cardb
  type: ClusterIP
status:
  loadBalancer: {}
