apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cardb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cardb
  template:
    metadata:
      labels:
        app: cardb
    spec:
      containers:
      - name: cardb
        image: fraj24/cardb
        ports:
        - containerPort: 8080
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: 
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 60
      - setWeight: 20
      - pause: {} 
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cardb
  name: cardb
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cardb
  type: ClusterIP
