apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cardb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cardb
  template:
    metadata:
      labels:
        app: cardb
    spec:
      containers:
      - name: cardb
        image: fraj24/cardb:16
        ports:
        - containerPort: 8080
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: 
      stableService: cardb-stable
      canaryService: cardb-canary
      steps:
      - setWeight: 50
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cardb
  name: cardb-stable
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cardb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cardb
  name: cardb-canary
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cardb
  type: ClusterIP
